image: python:3.6
stages:
  - test
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/
    - venv/

test:
  stage: test
  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - tools/get-credentials
  script:
    - pytest

test_externalapi:
  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - tools/get-credentials
  script:
    - pytest -m externalapi
  only:
    - schedules

build_docker_image:
  image: docker:stable
  services:
    - docker:dind
  stage: build
  before_script:
    - apk add --no-cache curl
    - tools/get-credentials
  script:
    - docker build -t api-converse .
    - docker run -v /builds/$CI_PROJECT_PATH/res/credentials:/app/res/credentials api-converse pytest
  only:
    - master
  tags:
    - docker
