image: python:3.6
stages:
  - test
  - build
  - deploy

pytest:
  stage: test
  before_script:
    - tools/get-credentials
    - pip install -r requirements.txt
  script:
    - pytest

pytest_externalapi:
  before_script:
    - tools/get-credentials
    - pip install -r requirements.txt
  script:
    - pytest -m externalapi
  only:
    - schedules

build_docker_image:
  image: docker:stable
  services:
    - docker:dind
  stage: build
  before_script:
    - apk add --no-cache curl
    - tools/get-credentials
  script:
    - docker build -t api-converse .
    - docker run -v ./res/credentials:/app/res/credentials api-converse pytest
  only:
    - master
  tags:
    - docker
