image: python:3.6
stages:
  - test
  - build
  - deploy

pytest:
  stage: test
  before_script:
    - tools/get-credentials
    - pip install -r requirements-dev.txt
  script:
    - pytest

pytest_externalapi:
  before_script:
    - tools/get-credentials
    - pip install -r requirements-dev.txt
  script:
    - pytest -m externalapi
  only:
    - schedules

build_docker_image:
  stage: build
  script:
    - docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWD
    - docker build -t surirobot/api-converse .
    - docker push surirobot/api-converse
  only:
    - master
