image: python:latest
stages:
  - test

cache:
  paths:
    - .cache/
    - venv/

test:
  stage: test
  variables: {}
  before_script:
    - tools/get-credentials
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements-dev.txt
  script:
    - pytest

test_externalapi:
  variables: {}
  before_script:
    - tools/get-credentials
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements-dev.txt
  script:
    - pytest -m externalapi
  only:
    - schedules
