image: python:3.6
stages:
  - test
  - build
  - release

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/
    - venv/

test:
  stage: test
  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - tools/get-credentials
  script:
    - pytest --cov=api

test_externalapi:
  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - tools/get-credentials
  script:
    - pytest -m externalapi
  only:
    - schedules

build_docker_image:
  image: docker:stable
  services:
    - docker:dind
  stage: build
  before_script:
    - apk add --no-cache curl
    - tools/get-credentials
  script:
    - docker build -t api-converse .
    - docker run -v /builds/$CI_PROJECT_PATH/res/credentials:/app/res/credentials --entrypoint pytest api-converse
  only:
    - master
  tags:
    - docker

mirror_to_github:
  stage: release
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GITHUB_DEPLOY_KEY")
    - ssh-keyscan -H github.com > ~/.ssh/known_hosts
    - git remote rm github || true
    - git remote add github $GITHUB_DEPLOY_URL
    - git fetch github
    - git push github HEAD:master --force
  only:
    - master
  except:
    - schedules

