image: python:3.6
stages:
  - test
  - build
  - github
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/
    - venv/

test:
  stage: test
  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - tools/get-credentials
  script:
    - pytest

test_externalapi:
  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - tools/get-credentials
  script:
    - pytest -m externalapi
  only:
    - schedules

build_docker_image:
  image: docker:stable
  services:
    - docker:dind
  stage: build
  before_script:
    - apk add --no-cache curl
    - tools/get-credentials
  script:
    - docker build -t api-converse .
    - docker run -v /builds/$CI_PROJECT_PATH/res/credentials:/app/res/credentials --entrypoint pytest api-converse
  only:
    - master
  tags:
    - docker

push_to_github:
  stage: github
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GITHUB_SSH_KEY")
    - git remote add github git@github.com:suricats/surirobot-api-converse.git
    - git push github master
  only:
    - master
