image: python:3.6
stages:
  - test

cache:
  paths:
    - .pip

test:
  stage: test
  variables: {}
  before_script:
    - mkdir -p .pip
    - pip --cache-dir=.pip install -r requirements-dev.txt
  script:
    - pytest

test_externalapi:
  variables: {}
  before_script:
    - mkdir -p .pip
    - pip --cache-dir=.pip install -r requirements-dev.txt
  script:
    - pytest -m externalapi
  only:
    - schedules
