image: python:latest
stages:
  - test

test:
  stage: test
  variables: {}
  before_script:
    - tools/get-credentials
    - pip install -r requirements-dev.txt
  script:
    - pytest

test_externalapi:
  variables: {}
  before_script:
    - tools/get-credentials
    - pip install -r requirements-dev.txt
  script:
    - pytest -m externalapi
  only:
    - schedules
